[package]
name = "echo-fs-read"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "harnless:plugin-fs-read"

[package.metadata.component.target.dependencies]
"wasi:filesystem" = { path = "wit/deps/filesystem.wit" }
"wasi:io" = { path = "wit/deps/io.wit" }
"wasi:clocks" = { path = "wit/deps/clocks.wit" }
